import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(channel="chrome", headless=False)
    context = browser.new_context(user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")
    page.goto("https://studio.youtube.com/channel/UCPTViCgyJPjWRDrDo5rBFCQ/videos/upload?filter=%5B%7B%22name%22%3A%22VISIBILITY%22%2C%22value%22%3A%5B%22DRAFT%22%5D%7D%5D&sort=%7B%22columnType%22%3A%22date%22%2C%22sortOrder%22%3A%22ASCENDING%22%7D")
    page.get_by_role("button", name="Detail").click()
    page.get_by_role("button", name="Gunakan kembali detail").click()
    page.locator(".thumbnail.style-scope.ytcp-entity-card").first.click()
    page.get_by_role("button", name="Gunakan kembali", exact=True).click()
    page.get_by_role("textbox", name="Tambahkan judul yang").click()
    page.get_by_role("textbox", name="Tambahkan judul yang").press("PageUp")
    page.get_by_role("textbox", name="Tambahkan judul yang").press("ArrowRight")
    page.get_by_role("textbox", name="Tambahkan judul yang").press("ArrowRight")
    page.get_by_role("textbox", name="Tambahkan judul yang").press("ArrowRight")
    page.get_by_role("textbox", name="Tambahkan judul yang").fill("123 PENGAJIAN KITAB RISALATUL MAYMUNIYAH - ABUYA UCI CILONGOK")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").click()
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("PageUp")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowDown")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowDown")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowDown")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowDown")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowDown")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowDown")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").click()
    page.get_by_role("textbox", name="Beri tahu penonton tentang").click()
    page.get_by_role("textbox", name="Beri tahu penonton tentang").click()
    page.get_by_role("textbox", name="Beri tahu penonton tentang").click()
    page.get_by_role("textbox", name="Beri tahu penonton tentang").click()
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowUp")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowUp")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowUp")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowUp")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowUp")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowUp")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowUp")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowUp")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowRight")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowRight")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowRight")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").press("ArrowRight")
    page.get_by_role("textbox", name="Beri tahu penonton tentang").fill("#RisalatulMaymuniyah #AbuyaUci #AbuyaUciTerbaru #AbuyaUciTurtusi #AbuyaUciCilongok #AbahUci #AbahUciCilongok \n\n\"123 PENGAJIAN KITAB RISALATUL MAYMUNIYAH - ABUYA UCI CILONGOK\".\n\nPengajian Mingguan Kitab Risalatul Maymuniyah  Yang Dibacakan Oleh Abuya Uci Turtusi di Pondok Pesantren Al Istiqlaliyah  Setiap Malam Sabtu Pukul 20:00 WIB.\n\nLihat Playlist Pengajian Abuya Uci Turtusi Terbaru !\n\nPengajian Abuya Uci Kitab Minhajut Tholibin\nhttps://www.youtube.com/playlist?list=PLXmr5FbVZORXfw4rxKxJ45k5xN0DiB39W\n\nPengajian Abuya Uci Kitab Ibanatul Ahkam\nhttps://www.youtube.com/playlist?list=PLXmr5FbVZORXMFWNkEbo6j7G3Lj6x928k\n\nPengajian Abuya Uci Kitab Tadzkirotul Qurtubi\nhttps://www.youtube.com/playlist?list=PLXmr5FbVZORV4wmN_XvPaLyUYg7o0AFk2\n\nPengajian Abuya Uci Kitab Sirrul Asror\nhttps://www.youtube.com/playlist?list=PLXmr5FbVZORU-85XY-YqcUbfTYCYKcrnt\n\nPengajian Abuya Uci Kitab Risalatul Maymuniyah\nhttps://www.youtube.com/playlist?list=PLXmr5FbVZORXq5Z9fIU3mUNY9u5FlVHUB\n\nPengajian Abuya Uci Kitab Tafsir Jalalain\nhttps://www.youtube.com/playlist?list=PLXmr5FbVZORV3Haj5deyJ2hzDsTcsURFX\n\n#abuyauci #abuyauciturtusi #abahuci #khuciturtusi #abuyauciterbaru #khuci #ngajiabuyauci #ceramahabuyauci #kiyaiuci #pengajianabuyauci #mamauciterbaru #abuyaucidzikir #abuyacilongok #abuyabanten #ngajisantri #ngajikitab #ngaji #ngajionline #santri #santrisunda #pengajian #pengajianabahuci #ngajimingguan #ngajisantri #pondokpesantren #ngajitasawuf #ngajifiqih #ngajitafsiralquran #ngajitafsir #ngajitafsirjalalain #ngajihadits #ngajihakekat #ngajithoriqoh #kitabkuning #minhajuttholibin #ibanatulahkam #sirrulasror #tafsirjalalain #risalatulmaymuniyah #tadzkirotulqurtubi")
    page.get_by_role("button", name="Upload file").click()
    page.locator("#file-loader").set_input_files("123 PENGAJIAN KITAB RISALATUL MAYMUNIYAH - ABUYA UCI CILONGOK-Thumbnail.jpg")
    page.get_by_role("button", name="Tampilkan setelan lanjutan").click()
    page.get_by_role("radio", name="Tidak, AI tidak digunakan").click()
    page.get_by_role("button", name="Tanggal perekaman Tidak ada").nth(1).click()
    page.get_by_text("1", exact=True).nth(2).click()
    page.get_by_role("button", name="Berikutnya", exact=True).click()
    page.locator(".m10n-text").click()
    page.get_by_role("radio", name="Aktif", exact=True).click()
    page.get_by_role("button", name="Selesai").click()
    page.get_by_role("button", name="Berikutnya", exact=True).click()
    page.get_by_text("Tidak satu pun di atas").click()
    page.get_by_role("button", name="Kirim rating").click()
    page.get_by_role("button", name="Berikutnya", exact=True).click()
    page.get_by_role("button", name="Impor dari video").click()
    page.locator(".thumbnail.style-scope.ytcp-entity-card").first.click()
    page.get_by_role("button", name="Simpan", exact=True).click()
    page.locator("#cards-button").get_by_role("button", name="Tambahkan").click()
    page.locator(".style-scope.ytve-info-cards-editor-options-panel > div:nth-child(3)").click()
    page.locator("ytcp-entity-card:nth-child(4) > #content > .thumbnail").click()
    page.get_by_role("button", name="Simpan", exact=True).click()
    page.get_by_role("button", name="Berikutnya", exact=True).click()
    page.get_by_role("button", name="Berikutnya", exact=True).click()
    page.get_by_text("Pilih tanggal untuk membuat").click()
    page.get_by_role("radio", name="Dari khusus pelanggan ke").click()
    page.get_by_role("button", name="Agu 2026").nth(1).click()
    page.get_by_text("30").nth(3).click()
    page.locator("#input-3").get_by_label("", exact=True).click()
    page.get_by_role("option", name="20.00").click()
    page.get_by_role("button", name="Jadwalkan").click()
    page.get_by_role("button", name="Tutup").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
